# Generated by Django 3.2.3 on 2021-05-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('duty', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500, null=True)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('surname', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('phone', models.IntegerField(default='')),
                ('date_of_birth', models.DateTimeField(default='')),
                ('study_title', models.CharField(choices=[('Diploma', 'Diploma'), ('Laurea', 'Laurea')], default='', max_length=7)),
                ('curriculum', models.FileField(upload_to='uploads')),
                ('job', models.ManyToManyField(to='form.Job')),
            ],
        ),
    ]
